/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "koa-mongodb-template",
  "description": "使用Koa和MongoDB搭建的一个通用的Node.js后台框架，助力前端成为全栈工程师",
  "base": "/koa-mongodb-template-site/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/koa-mongodb-template-site/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present Youxiubiji"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6076e076",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-55d43850",
      "path": "/guide/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "Github",
        "link": "https://github.com/youxiubiji/koa-mongodb-template"
      }
    ]
  }
}